import Head from "next/head";
export default function LoadingLayout() {
  return (
    <>
      <Head>
        <title>Loading</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className="navbar navbar-expand-lg navbar-dark bg-dark">
        <div className="container-fluid">
          <a className="navbar-brand" href="#">
            <img
              src={"/profile.png"}
              width="48"
              height="48"
              style={{ borderRadius: "5px", border: "1px solid white" }}
            />
          </a>
        </div>
      </nav>
      <main>
        <div className="text-center mt-4">
          <h4>Application is loading...</h4>
          <img src="/loading.gif" width={128} height={128} alt="loading icon" />
        </div>
      </main>
    </>
  );
}
